name: Check changelog changed
on:
  workflow_call:

jobs:
  changelog_changes:
    name: "Checking that changelog has changed"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v4
        with:
          submodules: 'recursive'
      - name: Get change status for CHANGELOG.md
        id: changed-changelog
        uses: tj-actions/changed-files@934b2d2c7e653bb8c968afed5a0428617f09aa24 # v45.0.5
        with:
          files: CHANGELOG.md
      - name: Failed if changelog not changed
        if: github.event.pull_request.user.login != 'renovate[bot]' && steps.changed-changelog.outputs.any_changed != 'true'
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v7
        with:
          script: core.setFailed('CHANGELOG.md has not changed! You need to write human-readable changes in each Pull Request')
